package class

type Class string

const (
	MISSILE          = "MISSILE"
	MONSTER          = "MONSTER"
	PLAYER           = "PLAYER"
	OBSTACLE         = "OBSTACLE"
	FOOD             = "FOOD"
	EXIT             = "EXIT"
	KEY              = "KEY"
	DOOR             = "DOOR"
	INFO_BOOK        = "INFO_BOOK"
	TRIGGER          = "TRIGGER"
	TRANSPORTER      = "TRANSPORTER"
	HOLE             = "HOLE"
	WAND             = "WAND"
	FIRE             = "FIRE"
	ELEVATOR         = "ELEVATOR"
	ELEVATOR_SHAFT   = "ELEVATOR_SHAFT"
	DANGEROUS        = "DANGEROUS"
	MONSTERGENERATOR = "MONSTERGENERATOR"
	READABLE         = "READABLE"
	LIGHT            = "LIGHT"
	SIMPLE           = "SIMPLE"
	COMPLEX          = "COMPLEX"
	IMMOBILE         = "IMMOBILE"
	VISIBLE_ENABLE   = "VISIBLE_ENABLE"
	WEAPON           = "WEAPON"
	ARMOR            = "ARMOR"
	NOT_STACKABLE    = "NOT_STACKABLE"
	TREASURE         = "TREASURE"
	FLAG             = "FLAG"
	CLIENT_PERSIST   = "CLIENT_PERSIST"
	CLIENT_PREDICT   = "CLIENT_PREDICT"
	PICKUP           = "PICKUP"
)
